# Generated by Django 5.2.17 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="หมวดหมู่ / MBTI / สถานะ",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="ชื่อที่แสดง (Display Name)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="music_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="เพลงโปรด / แท็กเสียง",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="music_url",
            field=models.URLField(
                blank=True, default="", max_length=300, verbose_name="URL เพลงโปรด"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="ชื่อลิงก์โปรไฟล์/โซเชียล",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="URL ลิงก์โปรไฟล์/โซเชียล",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="คำอธิบายโปรไฟล์ (Bio)",
            ),
        ),
    ]
