# Generated by Django 5.2.17 on 2026-09-05 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_category_profile_display_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="อีเมลที่รับ OTP"),
                ),
                (
                    "otp_code",
                    models.CharField(max_length=6, verbose_name="รหัส OTP 6 หลัก"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาที่สร้าง"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="เวลาหมดอายุ")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="ถูกใช้งานแล้วหรือไม่"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="จำนวนครั้งที่ลองกรอก"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_otps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP รีเซ็ตรหัสผ่าน",
                "verbose_name_plural": "OTP รีเซ็ตรหัสผ่านทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
