# Generated by Django 5.2.17 on 2026-08-30 15:44

import checkins.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_name",
                    models.CharField(max_length=200, verbose_name="ชื่อสถานที่"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="ละติจูด"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="ลองจิจูด"),
                ),
                (
                    "caption",
                    models.TextField(max_length=500, verbose_name="ข้อความบรรยาย"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=checkins.models.checkin_photo_path,
                        verbose_name="รูปภาพสถานที่",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขล่าสุด"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "เช็คอิน",
                "verbose_name_plural": "รายการเช็คอิน",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="checkins.checkin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "checkin")},
            },
        ),
    ]
