# Generated by Django 5.2.17 on 2026-08-30 21:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="รูปภาพสถานที่"
            ),
        ),
    ]
