# Generated by Django 5.2.17 on 2026-08-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0003_comment_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="province",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="จังหวัด"
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="region",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="ภูมิภาค"
            ),
        ),
    ]
