# Generated by Django 5.2.17 on 2026-09-04 14:27

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0004_checkin_province_checkin_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="aspect_ratio",
            field=models.CharField(
                choices=[
                    ("original", "ต้นฉบับ / พอดีเฟรม (Original / Smart Fit)"),
                    ("1:1", "1:1 สี่เหลี่ยมจัตุรัส (Square)"),
                    ("4:5", "4:5 แนวตั้งพอดีจอ (Portrait)"),
                    ("16:9", "16:9 แนวนอนมุมกว้าง (Landscape)"),
                    ("9:16", "9:16 แนวตั้งเต็มจอ (Story)"),
                ],
                default="original",
                max_length=20,
                verbose_name="สัดส่วนภาพ",
            ),
        ),
        migrations.CreateModel(
            name="CheckInImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="รูปภาพสถานที่"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ลำดับ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="checkins.checkin",
                        verbose_name="เช็คอิน",
                    ),
                ),
            ],
            options={
                "verbose_name": "รูปภาพเช็คอิน",
                "verbose_name_plural": "รูปภาพเช็คอินทั้งหมด",
                "ordering": ["order", "id"],
            },
        ),
    ]
