# Generated by Django 5.2.17 on 2026-09-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0006_alter_checkin_aspect_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="aspect_ratio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("original", "ต้นฉบับ / พอดีเฟรม (Original / Smart Fit)"),
                    ("1:1", "1:1 สี่เหลี่ยมจัตุรัส (Square)"),
                    ("4:5", "4:5 แนวตั้งพอดีจอ (Portrait)"),
                    ("16:9", "16:9 แนวนอนมุมกว้าง (Landscape)"),
                    ("9:16", "9:16 แนวตั้งเต็มจอ (Full Screen)"),
                ],
                default="original",
                max_length=20,
                verbose_name="สัดส่วนภาพ",
            ),
        ),
    ]
