# Generated by Django 5.2.17 on 2026-09-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0007_alter_checkin_aspect_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="show_user_location",
            field=models.BooleanField(
                default=False, verbose_name="แสดงตำแหน่งผู้โพสต์จริงบนแผนที่"
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="user_latitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ละติจูดผู้โพสต์จริง"
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="user_longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ลองจิจูดผู้โพสต์จริง"
            ),
        ),
    ]
